version: "3"

services:
  app:
    image: powerdnsadmin/pda-legacy:latest
    container_name: powerdns_admin
    ports:
      - "9191:80"
    logging:
      driver: json-file
      options:
        max-size: 50m
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://pda:changeme@db/pda
      - SECRET_KEY=replace_me_with_something_random
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=your-email@gmail.com
      - SMTP_PASSWORD=your-app-password
      - SMTP_FROM_ADDRESS=your-email@gmail.com
      - SMTP_USE_TLS=True
      - SMTP_USE_SSL=False
      - GUNICORN_TIMEOUT=60
      - GUNICORN_WORKERS=2
      - GUNICORN_LOGLEVEL=DEBUG
      - ADMIN_EMAIL=admin@example.com
      - PORT_MONITOR_INTERVAL=60
      - MONITORED_PORTS=53,80,443
